### ISSUE TITLE
Unable to load SNAVXBee2 binding in Eclipse Smart Home

### ISSUE THREAD

**Issue by amarpulli1994** [g1velo/SNAVXbee2#10]
Hello @g1velo,

I am trying to load snavxbee2 binding of jar file into Eclipse smart home. When I could run the Eclipse Smart Home Server, jar file doesn't Active in ESH. 
log file:

```
2017-06-01 14:12:57,820 | ERROR | lixDispatchQueue | snavxbee2                        | 206 - org.openhab.binding.snavxbee2 - 2.0.2.201706011411 | FrameworkEvent ERROR - org.openhab.binding.snavxbee2
org.osgi.framework.BundleException: Unable to resolve org.openhab.binding.snavxbee2 [206](R 206.0): missing requirement [org.openhab.binding.snavxbee2 [206](R 206.0)] osgi.wiring.package; (osgi.wiring.package=org.openhab.core.items) Unresolved requirements: [[org.openhab.binding.snavxbee2 [206](R 206.0)] osgi.wiring.package; (osgi.wiring.package=org.openhab.core.items)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)[org.apache.felix.framework-5.4.0.jar:]
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)[org.apache.felix.framework-5.4.0.jar:]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121] 
```
bundle list

```
195 | Active    |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb.asm
201 | Active    |  80 | 2.1.0.201704141547    | HABPanel User Interface
202 | Active    |  80 | 2.0.0.b3              | openHAB Dashboard UI
204 | Active    |  80 | 2.0.0.b3              | openHAB Serial Transport Bundle
206 | Installed |  80 | 2.0.2.201706011411    | SNAVXbee2 Binding
```
How I could resolve this issues. 

Thanks,
Amar.

**Comment by kirantpatil** [comment]
I believe it is issue in Windows maven installer. In Ubuntu it loads and shows "Active" state. Please try it wit other version of Maven or on Ubuntu.

**Comment by maggu2810** [comment]
The error message states that the wiring for package "org.openhab.core.items" fails.
So, check if you have installed the openHAB Bundle that export that package (I assume the core one).

If you want to use openHAB bundles, you should (perhaps) use the openHAB distribution.

**Comment by amarpulli1994** [comment]
Thanks @maggu2810 ,
Now it's working fine for me.
 I just remove `org.openhab.core.items` from my manifest file.
Thanks and Regards,
Amar.

**Comment by maggu2810** [comment]
The manifest file has to contain all packages in its Import-Package section that needs to be imported...

If there are entries in the manifest that are not needed they should be removed.
If you remove it from the manifest file but the package is used at some time then the wiring will succeed, but you will receive an exception on runtime.
