### ISSUE TITLE
[How To] Installation on Eclipse Smarthome

### ISSUE THREAD

**Issue by kirantpatil** [g1velo/SNAVXbee2#3]
Hi Sir,

Please provide us the way to compile the and test the code on [Eclipse Smarthome](https://github.com/eclipse/smarthome-packaging-sample).

Thanks.

**Comment by kirantpatil** [comment]
snavxbee binding was expecting dependency gun.io to which I downloaded org.openhab.io.transport.serial-2.0.0.b3 jar file.

I added below jar files in " runtime/concierge/system/" directory and updated "runtime/concierge/smarthome.xargs" as below.

-istart ${system.dir}/org.openhab.io.transport.serial-2.0.0.b3*.jar
-istart ${system.dir}/org.openhab.binding.snavxbee2_2.0.1.201701171601*.jar


Now I am getting below issue.
```

$ sh start.sh
Using java: /usr/lib/jvm/java-8-oracle/bin/java
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
JAVA_COMPACT_PROFILE=fulljre
JAVA_VENDOR=Oracle
---------------------------------------------------------
  Concierge OSGi 5.0.0 on Linux 3.19.0-79-generic starting ... (eclipse-smarthome) startlevel=3
---------------------------------------------------------
---------------------------------------------------------
  Framework started in 0.0 seconds.
---------------------------------------------------------

Concierge> 2017-01-31 17:06:50.301 [INFO   ] [org.eclipse.jetty.util.log.Log initialized] - Logging initialized @3648ms
2017-01-31 17:06:50.452 [INFO   ] [org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper startJettyAtJettyHome] - Configuring the default jetty server with [file:/home/fabritronix/eclipse_smart-home/runtime/etc/jetty.xml, file:/home/fabritronix/eclipse_smart-home/runtime/etc/jetty-deployer.xml, file:/home/fabritronix/eclipse_smart-home/runtime/etc/jetty-selector.xml]
2017-01-31 17:06:50.454 [INFO   ] [org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper startJettyAtJettyHome] - JETTY.HOME=/home/fabritronix/eclipse_smart-home/runtime
2017-01-31 17:06:50.455 [INFO   ] [org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper startJettyAtJettyHome] - JETTY.BASE=/home/fabritronix/eclipse_smart-home/runtime
2017-01-31 17:06:50.864 [INFO   ] [org.eclipse.jetty.server.Server doStart] - jetty-9.3.z-SNAPSHOT
2017-01-31 17:06:51.936 [INFO   ] [org.eclipse.jetty.server.AbstractConnector doStart] - Started 0.0.0.0:8443@6e0fae0{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2017-01-31 17:06:51.940 [INFO   ] [org.eclipse.jetty.server.AbstractConnector doStart] - Started ServerConnector@7aaca91a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2017-01-31 17:06:51.943 [INFO   ] [org.eclipse.jetty.server.Server doStart] - Started @5310ms
2017-01-31 17:06:51.945 [INFO   ] [org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper startJettyAtJettyHome] - Default jetty server configured
2017-01-31 17:06:52.157 [INFO   ] [org.eclipse.jetty.server.handler.ContextHandler doStart] - Started o.e.j.s.ServletContextHandler@512baff6{/,null,AVAILABLE}
2017-01-31 17:06:56.271 [INFO   ] [org.eclipse.smarthome.ui.paper.internal.PaperUIApp activate] - Started Paper UI at /paperui
2017-01-31 17:06:56.424 [SEVERE ] [org.eclipse.smarthome.core.service.AbstractWatchService initializeWatchService] - Cannot activate folder watcher for folder '/home/fabritronix/eclipse_smart-home/conf/services': /home/fabritronix/eclipse_smart-home/conf/services
2017-01-31 17:06:56.627 [INFO   ] [org.jupnp.UpnpServiceImpl startup   ] - Starting UPnP service...
2017-01-31 17:06:56.695 [INFO   ] [org.jupnp.transport.impl.osgi.HttpServiceServletContainerAdapter registerServlet] - Registering UPnP callback servlet as /upnpcallback
Exception in thread "main" org.osgi.framework.BundleException: Resolution failed [BundleRequirement{Import-Package org.osgi.framework;version="1.8.0"}]
	at org.eclipse.concierge.Concierge.resolve(Concierge.java:2645)
	at org.eclipse.concierge.BundleImpl$Revision.resolve(BundleImpl.java:1881)
	at org.eclipse.concierge.BundleImpl.activate(BundleImpl.java:532)
	at org.eclipse.concierge.BundleImpl.start(BundleImpl.java:506)
	at org.eclipse.concierge.BundleImpl.start(BundleImpl.java:444)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsInputStream(XargsFileLauncher.java:169)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsFile(XargsFileLauncher.java:70)
	at org.eclipse.concierge.Concierge.doMain(Concierge.java:606)
	at org.eclipse.concierge.Concierge.main(Concierge.java:525)

```

**Comment by kirantpatil** [comment]
I used https://github.com/maggu2810/smarthome-packaging-sample-karaf to run ESH.

I installed below jar files as below and run 'bin/karaf' to install them.

```
$ pwd
/home/fabritronix/smarthome-packaging-sample-karaf/target/assembly/deploy
$ ls
org.openhab.binding.snavxbee2_2.0.1.201701171601.jar  org.openhab.io.transport.serial-2.0.0.b3.jar  README
```

```
karaf@root()> bundle:list
START LEVEL 100 , List Threshold: 50
 ID | State  | Lvl | Version               | Name
-----------------------------------------------------------------------------------------------
  9 | Active |  80 | 2.3.0.201506221200    | JAX-RS Gson Provider
 10 | Active |  80 | 5.3.1.201602281253    | OSGi JAX-RS Connector
 11 | Active |  80 | 2.3.1                 | Gson
 12 | Active |  80 | 18.0.0                | Guava: Google Core Libraries for Java
 13 | Active |  80 | 3.0.0.v201312141243   | Google Guice (No AOP)
 14 | Active |  80 | 1.5.8                 | swagger-annotations
 15 | Active |  80 | 3.19.0.GA             | Javassist
 19 | Active |  80 | 1.1.0.Final           | Bean Validation API
 21 | Active |  80 | 2.0.1                 | javax.ws.rs-api
 23 | Active |  80 | 3.2.0.v201101311130   | ANTLR Runtime
 37 | Active |  80 | 1.6.0                 | Commons Codec
 38 | Active |  80 | 3.2.1                 | Commons Collections
 39 | Active |  80 | 1.1                   | Commons Exec
 40 | Active |  80 | 2.2.0                 | Commons IO
 41 | Active |  80 | 2.6                   | Commons Lang
 48 | Active |  80 | 4.2.3                 | Apache HttpClient OSGi bundle
 49 | Active |  80 | 4.2.3                 | Apache HttpCore OSGi bundle
 82 | Active |  80 | 3.1.0.7               | Apache ServiceMix :: Bundles :: commons-httpclient
 87 | Active |  80 | 2.11.0.v20150805-0538 | EMF Common
 88 | Active |  80 | 2.11.1.v20150805-0538 | EMF Ecore
 89 | Active |  80 | 2.11.1.v20150805-0538 | EMF XML/XMI Persistence
 90 | Active |  80 | 3.7.0.v20150402-1709  | Common Eclipse Runtime
 91 | Active |  80 | 3.6.0.v20150318-1503  | Extension Registry Support
 92 | Active |  80 | 1.6.0.v20141009-1504  | Supplemental Equinox Functionality
118 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation API
119 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation commands
120 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation Core
121 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation Module Core
122 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation Module Script
123 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation Script Globals
124 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation Module Timer
125 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation GSON Parser
126 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation Providers
127 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Automation REST API
128 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Config Core
129 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Configuration Discovery
130 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Config Dispatcher
131 | Active |  75 | 0.9.0.201702010824    | Eclipse SmartHome Config XML
132 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core
133 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core Audio
134 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome AutoUpdate Binding
135 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core Binding XML
136 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core ID
137 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core Persistence
138 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Scheduler Service
139 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core Thing
140 | Active |  75 | 0.9.0.201702010824    | Eclipse SmartHome Core Thing XML
141 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Transformation Service
142 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core Voice
143 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Console
144 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Console for OSGi runtime Karaf
145 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Monitor
146 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Net I/O Bundle
147 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome REST Interface Bundle
148 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Core REST API
149 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Sitemap REST API
150 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome SSE REST API
151 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Model Core
152 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Item Model
153 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Item Model Runtime
154 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Persistence Model
155 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Persistence Runtime
156 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Rule Model
157 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Rule Runtime
158 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Script
159 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Script Runtime
160 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Sitemap Model
161 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Sitemap Runtime
162 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Thing Model
163 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Thing Model Runtime
164 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome MapDB Storage Service
165 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome UI
166 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome UI Icons
167 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Classic IconSet
168 | Active |  80 | 0.9.0.201702010824    | Eclipse SmartHome Paper UI
169 | Active |  80 | 2.9.2                 | Xtend Runtime Library
170 | Active |  80 | 2.9.2                 | Xtend Macro Interfaces
171 | Active |  80 | 2.9.2                 | Xtext
172 | Active |  80 | 2.9.2                 | Xtext Common Types
173 | Active |  80 | 2.9.2                 | JSR-45 Smap installer
174 | Active |  80 | 2.9.2                 | Xtext Utility
175 | Active |  80 | 2.9.2.v20160428-1452  | Xbase Model
176 | Active |  80 | 2.9.2                 | Xbase Runtime Library
192 | Active |  80 | 2.2.0                 | JUPnP Library
193 | Active |  80 | 1.9.6                 | MIME streaming extension
194 | Active |  80 | 1.0.9                 | mapdb
195 | Active |  80 | 5.0.2                 | Require-Bundle Fix :: org.objectweb.asm
203 | Active |  80 | 2.0.1.201701171601    | SNAVXbee2 Binding
204 | Active |  80 | 2.0.0.b3              | openHAB Serial Transport Bundle
karaf@root()> 
```

![screenshot from 2017-02-07 15 28 00](https://cloud.githubusercontent.com/assets/1178055/22686458/3c114052-ed4a-11e6-98a0-99cac7b587d1.png)
